Set required timeout_minutes to please nick fields retry action #patch
An attempt to fix

> Error: Must specify either timeout_minutes or timeout_seconds inputs

https://github.com/svvsaga/saga/actions/runs/3511303636/jobs/5881948698#step:6:24

10 minutes is a little more than a usual "run all integration tests
nightly" run.